--[=[
 d888b  db    db d888888b      .d888b.      db      db    db  .d8b.  
88' Y8b 88    88   `88'        VP  `8D      88      88    88 d8' `8b 
88      88    88    88            odD'      88      88    88 88ooo88 
88  ooo 88    88    88          .88'        88      88    88 88~~~88 
88. ~8~ 88b  d88   .88.        j88.         88booo. 88b  d88 88   88    @uniquadev
 Y888P  ~Y8888P' Y888888P      888888D      Y88888P ~Y8888P' YP   YP  CONVERTER 

designed using localmaze gui creator
]=]

-- Instances: 41 | Scripts: 0 | Modules: 0 | Tags: 0
local LMG2L = {};

-- Players.giruoh_jgry.PlayerGui.ScreenGui
LMG2L["ScreenGui_1"] = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"));
LMG2L["ScreenGui_1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame
LMG2L["Frame_2"] = Instance.new("Frame", LMG2L["ScreenGui_1"]);
LMG2L["Frame_2"]["BorderSizePixel"] = 0;
LMG2L["Frame_2"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["Frame_2"]["Size"] = UDim2.new(0, 584, 0, 354);
LMG2L["Frame_2"]["Position"] = UDim2.new(0, 34, 0, 8);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.UICorner
LMG2L["UICorner_3"] = Instance.new("UICorner", LMG2L["Frame_2"]);
LMG2L["UICorner_3"]["CornerRadius"] = UDim.new(0, 10);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel
LMG2L["ImageLabel_4"] = Instance.new("ImageLabel", LMG2L["Frame_2"]);
LMG2L["ImageLabel_4"]["BorderSizePixel"] = 0;
LMG2L["ImageLabel_4"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- LMG2L["ImageLabel_4"]["ImageContent"] = ;
LMG2L["ImageLabel_4"]["Image"] = [[rbxassetid://108689301385143]];
LMG2L["ImageLabel_4"]["Size"] = UDim2.new(0, 584, 0, 354);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.TextButton4
LMG2L["TextButton4_5"] = Instance.new("TextButton", LMG2L["ImageLabel_4"]);
LMG2L["TextButton4_5"]["TextWrapped"] = true;
LMG2L["TextButton4_5"]["BorderSizePixel"] = 0;
LMG2L["TextButton4_5"]["TextScaled"] = true;
LMG2L["TextButton4_5"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton4_5"]["BackgroundColor3"] = Color3.fromRGB(179, 179, 179);
LMG2L["TextButton4_5"]["Size"] = UDim2.new(0, 116, 0, 28);
LMG2L["TextButton4_5"]["Text"] = [[clear]];
LMG2L["TextButton4_5"]["Name"] = [[TextButton4]];
LMG2L["TextButton4_5"]["Position"] = UDim2.new(0, 126, 0, 302);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame
LMG2L["ScrollingFrame_6"] = Instance.new("ScrollingFrame", LMG2L["ImageLabel_4"]);
LMG2L["ScrollingFrame_6"]["ScrollingDirection"] = Enum.ScrollingDirection.Y;
LMG2L["ScrollingFrame_6"]["BorderSizePixel"] = 0;
LMG2L["ScrollingFrame_6"]["BackgroundColor3"] = Color3.fromRGB(128, 128, 128);
LMG2L["ScrollingFrame_6"]["Size"] = UDim2.new(0, 152, 0, 252);
LMG2L["ScrollingFrame_6"]["Position"] = UDim2.new(0, 430, 0, 78);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton9
LMG2L["TextButton9_7"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton9_7"]["BorderSizePixel"] = 0;
LMG2L["TextButton9_7"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton9_7"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton9_7"]["Text"] = [[project duck utg]];
LMG2L["TextButton9_7"]["Name"] = [[TextButton9]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton15
LMG2L["TextButton15_8"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton15_8"]["BorderSizePixel"] = 0;
LMG2L["TextButton15_8"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton15_8"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton15_8"]["Text"] = [[9/11 plane]];
LMG2L["TextButton15_8"]["Name"] = [[TextButton15]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton17
LMG2L["TextButton17_9"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton17_9"]["BorderSizePixel"] = 0;
LMG2L["TextButton17_9"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton17_9"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton17_9"]["Text"] = [[chara]];
LMG2L["TextButton17_9"]["Name"] = [[TextButton17]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton7
LMG2L["TextButton7_a"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton7_a"]["BorderSizePixel"] = 0;
LMG2L["TextButton7_a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton7_a"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton7_a"]["Text"] = [[SEGMA V4]];
LMG2L["TextButton7_a"]["Name"] = [[TextButton7]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton18
LMG2L["TextButton18_b"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton18_b"]["BorderSizePixel"] = 0;
LMG2L["TextButton18_b"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton18_b"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton18_b"]["Text"] = [[dominant]];
LMG2L["TextButton18_b"]["Name"] = [[TextButton18]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton2
LMG2L["TextButton2_c"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton2_c"]["BorderSizePixel"] = 0;
LMG2L["TextButton2_c"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_c"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton2_c"]["Text"] = [[OUCH SIMSOMP]];
LMG2L["TextButton2_c"]["Name"] = [[TextButton2]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton4
LMG2L["TextButton4_d"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton4_d"]["BorderSizePixel"] = 0;
LMG2L["TextButton4_d"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton4_d"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton4_d"]["Text"] = [[project zaga]];
LMG2L["TextButton4_d"]["Name"] = [[TextButton4]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton24
LMG2L["TextButton24_e"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton24_e"]["BorderSizePixel"] = 0;
LMG2L["TextButton24_e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton24_e"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton24_e"]["Text"] = [[project two bfdi]];
LMG2L["TextButton24_e"]["Name"] = [[TextButton24]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton8
LMG2L["TextButton8_f"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton8_f"]["BorderSizePixel"] = 0;
LMG2L["TextButton8_f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton8_f"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton8_f"]["Text"] = [[project eluaria]];
LMG2L["TextButton8_f"]["Name"] = [[TextButton8]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton21
LMG2L["TextButton21_10"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton21_10"]["BorderSizePixel"] = 0;
LMG2L["TextButton21_10"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton21_10"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton21_10"]["Text"] = [[project stigma]];
LMG2L["TextButton21_10"]["Name"] = [[TextButton21]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton12
LMG2L["TextButton12_11"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton12_11"]["BorderSizePixel"] = 0;
LMG2L["TextButton12_11"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton12_11"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton12_11"]["Text"] = [[1×1×1×1×1hax gui v2]];
LMG2L["TextButton12_11"]["Name"] = [[TextButton12]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton23
LMG2L["TextButton23_12"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton23_12"]["BorderSizePixel"] = 0;
LMG2L["TextButton23_12"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton23_12"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton23_12"]["Text"] = [[project sligma]];
LMG2L["TextButton23_12"]["Name"] = [[TextButton23]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton16
LMG2L["TextButton16_13"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton16_13"]["BorderSizePixel"] = 0;
LMG2L["TextButton16_13"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton16_13"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton16_13"]["Text"] = [[giant size destroyer]];
LMG2L["TextButton16_13"]["Name"] = [[TextButton16]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton20
LMG2L["TextButton20_14"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton20_14"]["BorderSizePixel"] = 0;
LMG2L["TextButton20_14"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton20_14"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton20_14"]["Text"] = [[sigma gui private]];
LMG2L["TextButton20_14"]["Name"] = [[TextButton20]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton11
LMG2L["TextButton11_15"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton11_15"]["BorderSizePixel"] = 0;
LMG2L["TextButton11_15"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton11_15"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton11_15"]["Text"] = [[poongui by redkid]];
LMG2L["TextButton11_15"]["Name"] = [[TextButton11]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton6
LMG2L["TextButton6_16"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton6_16"]["BorderSizePixel"] = 0;
LMG2L["TextButton6_16"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton6_16"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton6_16"]["Text"] = [[project segma v2]];
LMG2L["TextButton6_16"]["Name"] = [[TextButton6]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton10
LMG2L["TextButton10_17"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton10_17"]["BorderSizePixel"] = 0;
LMG2L["TextButton10_17"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton10_17"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton10_17"]["Text"] = [[ss and febypass]];
LMG2L["TextButton10_17"]["Name"] = [[TextButton10]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton14
LMG2L["TextButton14_18"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton14_18"]["BorderSizePixel"] = 0;
LMG2L["TextButton14_18"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton14_18"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton14_18"]["Text"] = [[EXTERNAL 1!1!]];
LMG2L["TextButton14_18"]["Name"] = [[TextButton14]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton5
LMG2L["TextButton5_19"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton5_19"]["BorderSizePixel"] = 0;
LMG2L["TextButton5_19"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton5_19"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton5_19"]["Text"] = [[private 1×1 v7.1.0]];
LMG2L["TextButton5_19"]["Name"] = [[TextButton5]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton3
LMG2L["TextButton3_1a"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton3_1a"]["BorderSizePixel"] = 0;
LMG2L["TextButton3_1a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton3_1a"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton3_1a"]["Text"] = [[SUMSUNG NOTE]];
LMG2L["TextButton3_1a"]["Name"] = [[TextButton3]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton19
LMG2L["TextButton19_1b"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton19_1b"]["BorderSizePixel"] = 0;
LMG2L["TextButton19_1b"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton19_1b"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton19_1b"]["Text"] = [[rc7 2016]];
LMG2L["TextButton19_1b"]["Name"] = [[TextButton19]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.UIListLayout
LMG2L["UIListLayout_1c"] = Instance.new("UIListLayout", LMG2L["ScrollingFrame_6"]);



-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton
LMG2L["TextButton_1d"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton_1d"]["TextWrapped"] = true;
LMG2L["TextButton_1d"]["BorderSizePixel"] = 0;
LMG2L["TextButton_1d"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_1d"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton_1d"]["Text"] = [[1×1 max mini gui]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton13
LMG2L["TextButton13_1e"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton13_1e"]["BorderSizePixel"] = 0;
LMG2L["TextButton13_1e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton13_1e"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton13_1e"]["Text"] = [[mang0 gui]];
LMG2L["TextButton13_1e"]["Name"] = [[TextButton13]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame.TextButton22
LMG2L["TextButton22_1f"] = Instance.new("TextButton", LMG2L["ScrollingFrame_6"]);
LMG2L["TextButton22_1f"]["BorderSizePixel"] = 0;
LMG2L["TextButton22_1f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton22_1f"]["Size"] = UDim2.new(0, 140, 0, 30);
LMG2L["TextButton22_1f"]["Text"] = [[shiba old]];
LMG2L["TextButton22_1f"]["Name"] = [[TextButton22]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.UICorner
LMG2L["UICorner_20"] = Instance.new("UICorner", LMG2L["ImageLabel_4"]);
LMG2L["UICorner_20"]["CornerRadius"] = UDim.new(0, 10);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.TextButton2
LMG2L["TextButton2_21"] = Instance.new("TextButton", LMG2L["ImageLabel_4"]);
LMG2L["TextButton2_21"]["TextWrapped"] = true;
LMG2L["TextButton2_21"]["BorderSizePixel"] = 0;
LMG2L["TextButton2_21"]["TextScaled"] = true;
LMG2L["TextButton2_21"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_21"]["BackgroundColor3"] = Color3.fromRGB(179, 179, 179);
LMG2L["TextButton2_21"]["Size"] = UDim2.new(0, 116, 0, 28);
LMG2L["TextButton2_21"]["Text"] = [[coming soon]];
LMG2L["TextButton2_21"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_21"]["Position"] = UDim2.new(0, 124, 0, 42);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.TextButton5
LMG2L["TextButton5_22"] = Instance.new("TextButton", LMG2L["ImageLabel_4"]);
LMG2L["TextButton5_22"]["TextWrapped"] = true;
LMG2L["TextButton5_22"]["BorderSizePixel"] = 0;
LMG2L["TextButton5_22"]["TextScaled"] = true;
LMG2L["TextButton5_22"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton5_22"]["BackgroundColor3"] = Color3.fromRGB(179, 179, 179);
LMG2L["TextButton5_22"]["Size"] = UDim2.new(0, 118, 0, 28);
LMG2L["TextButton5_22"]["Text"] = [[load]];
LMG2L["TextButton5_22"]["Name"] = [[TextButton5]];
LMG2L["TextButton5_22"]["Position"] = UDim2.new(0, 244, 0, 302);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.TextLabel
LMG2L["TextLabel_23"] = Instance.new("TextLabel", LMG2L["ImageLabel_4"]);
LMG2L["TextLabel_23"]["TextWrapped"] = true;
LMG2L["TextLabel_23"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_23"]["TextScaled"] = true;
LMG2L["TextLabel_23"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_23"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_23"]["BackgroundTransparency"] = 1;
LMG2L["TextLabel_23"]["Size"] = UDim2.new(0, 318, 0, 30);
LMG2L["TextLabel_23"]["Text"] = [[Project Can't think of a name 🤔🤔 by 00script]];
LMG2L["TextLabel_23"]["Position"] = UDim2.new(0, 44, 0, 4);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.TextButton3
LMG2L["TextButton3_24"] = Instance.new("TextButton", LMG2L["ImageLabel_4"]);
LMG2L["TextButton3_24"]["TextWrapped"] = true;
LMG2L["TextButton3_24"]["BorderSizePixel"] = 0;
LMG2L["TextButton3_24"]["TextScaled"] = true;
LMG2L["TextButton3_24"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton3_24"]["BackgroundColor3"] = Color3.fromRGB(179, 179, 179);
LMG2L["TextButton3_24"]["Size"] = UDim2.new(0, 116, 0, 28);
LMG2L["TextButton3_24"]["Text"] = [[execute]];
LMG2L["TextButton3_24"]["Name"] = [[TextButton3]];
LMG2L["TextButton3_24"]["Position"] = UDim2.new(0, 6, 0, 302);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame2
LMG2L["ScrollingFrame2_25"] = Instance.new("ScrollingFrame", LMG2L["ImageLabel_4"]);
LMG2L["ScrollingFrame2_25"]["ScrollingDirection"] = Enum.ScrollingDirection.Y;
LMG2L["ScrollingFrame2_25"]["BorderSizePixel"] = 0;
LMG2L["ScrollingFrame2_25"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["ScrollingFrame2_25"]["Name"] = [[ScrollingFrame2]];
LMG2L["ScrollingFrame2_25"]["VerticalScrollBarPosition"] = Enum.VerticalScrollBarPosition.Left;
LMG2L["ScrollingFrame2_25"]["Size"] = UDim2.new(0, 420, 0, 218);
LMG2L["ScrollingFrame2_25"]["Position"] = UDim2.new(0, 4, 0, 78);
LMG2L["ScrollingFrame2_25"]["BackgroundTransparency"] = 1;


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.ScrollingFrame2.TextBox
LMG2L["TextBox_26"] = Instance.new("TextBox", LMG2L["ScrollingFrame2_25"]);
LMG2L["TextBox_26"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextBox_26"]["BorderSizePixel"] = 0;
LMG2L["TextBox_26"]["TextSize"] = 10;
LMG2L["TextBox_26"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextBox_26"]["TextYAlignment"] = Enum.TextYAlignment.Top;
LMG2L["TextBox_26"]["BackgroundColor3"] = Color3.fromRGB(77, 77, 77);
LMG2L["TextBox_26"]["RichText"] = true;
LMG2L["TextBox_26"]["MultiLine"] = true;
LMG2L["TextBox_26"]["ClearTextOnFocus"] = false;
LMG2L["TextBox_26"]["PlaceholderText"] = [[-- script by 00script --]];
LMG2L["TextBox_26"]["Size"] = UDim2.new(0, 406, 0, 780);
LMG2L["TextBox_26"]["Position"] = UDim2.new(0, 14, 0, 0);
LMG2L["TextBox_26"]["Text"] = [[]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.TextButton
LMG2L["TextButton_27"] = Instance.new("TextButton", LMG2L["ImageLabel_4"]);
LMG2L["TextButton_27"]["TextWrapped"] = true;
LMG2L["TextButton_27"]["BorderSizePixel"] = 0;
LMG2L["TextButton_27"]["TextScaled"] = true;
LMG2L["TextButton_27"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_27"]["BackgroundColor3"] = Color3.fromRGB(179, 179, 179);
LMG2L["TextButton_27"]["Size"] = UDim2.new(0, 116, 0, 28);
LMG2L["TextButton_27"]["Text"] = [[home]];
LMG2L["TextButton_27"]["Position"] = UDim2.new(0, 4, 0, 42);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.ImageLabel.TextButton6
LMG2L["TextButton6_28"] = Instance.new("TextButton", LMG2L["ImageLabel_4"]);
LMG2L["TextButton6_28"]["TextWrapped"] = true;
LMG2L["TextButton6_28"]["BorderSizePixel"] = 0;
LMG2L["TextButton6_28"]["TextScaled"] = true;
LMG2L["TextButton6_28"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton6_28"]["BackgroundColor3"] = Color3.fromRGB(179, 179, 179);
LMG2L["TextButton6_28"]["Size"] = UDim2.new(0, 60, 0, 28);
LMG2L["TextButton6_28"]["Text"] = [[re]];
LMG2L["TextButton6_28"]["Name"] = [[TextButton6]];
LMG2L["TextButton6_28"]["Position"] = UDim2.new(0, 364, 0, 302);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.Frame.UIDragDetector
LMG2L["UIDragDetector_29"] = Instance.new("UIDragDetector", LMG2L["Frame_2"]);

-- SERVICES
local player = game:GetService("Players").LocalPlayer

-- UI
local textbox = LMG2L["TextBox_26"]
local executeBtn = LMG2L["TextButton3_24"]
local clearBtn = LMG2L["TextButton4_5"]
local loadBtn = LMG2L["TextButton5_22"]
local reBtn = LMG2L["TextButton6_28"]

-- EXECUTE FUNCTION
executeBtn.MouseButton1Click:Connect(function()
	local code = textbox.Text
	
	if code ~= "" then
		local func, err = loadstring(code)
		
		if func then
			pcall(func)
		else
			warn("Error: "..err)
		end
	end
end)

-- CLEAR FUNCTION
clearBtn.MouseButton1Click:Connect(function()
	textbox.Text = ""
end)

loadBtn.MouseButton1Click:Connect(function()
    local success, result = pcall(function()
        return game:HttpGet("https://pastebin.com/raw/7bZyYKCW", true)
    end)

    if success then
        local func, err = loadstring(result)
        if func then
            pcall(func)
        else
            warn(err)
        end
    else
        warn("HttpGet failed")
    end
end)

rebtn.MouseButton1Click:Connect(function()
if game.Players.LocalPlayer.Character then
game.Players.LocalPlayer.Character.Humanoid.Health = 0
end
end)


return LMG2L["ScreenGui_1"], require;
